### ISSUE TITLE
db.opt issue

### ISSUE THREAD

**Issue by HashimThePassionate** [AhmadFaraz83/Colleage#2]
### Steps to Reproduce
2. Click on '...'
3. Scroll down to '...'

### Actual Behavior
A clear and concise description of what actually happens.

### Environment
- OS: [e.g. Windows, MacOS, Linux]
- Browser [e.g. Chrome, Safari]

**Comment by AhmadFaraz83** [comment]
I reviewed this issue and it is a bug file  issue in db.opt
